name: comercial_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/bottm_nav/
    - assets/images/carousel_banner/

  fonts:
    - family: LondrinaSolid
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Jomolhari
      fonts:
        - asset: assets/fonts/Jomolhari-Regular.ttf
